import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import style from '../styles/Header.module.scss';
import mylogo from '../public/logo.png'
import Link from 'next/link';

const Header = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id={style.headerWrap}>
                <div id={style.headerTopWrap} className="fwidth">
                    <div id={style.headerTop} className="container">
                        <div className={style.socialInfoWrap}>
                            <a href='#' className='icon-facebook'></a>
                            <a href='#' className='icon-twitter'></a>
                            <a href='#' className='icon-youtube-play'></a>
                            <a href='#' className='icon-pinterest'></a>
                            <a href='#' className='icon-instagram'></a>
                            <a href='#' className='icon-linkedin'></a>
                        </div>
                        <div className={style.contactInfoWrap}>
                            <div className={style.contactInfo + " icon-phone"}>+880 1681509033</div>
                            <div className={style.contactInfo + " icon-clock"}>Mon-Fri 9:00 am - 7:00 pm</div>
                            <div className={style.contactInfo + " icon-mail"}>assunnahhijama@gmail.com</div>
                            <div className={style.contactInfo + " " + style.resForm}>Reservation Form</div>
                        </div>
                    </div>
                </div>
                <div className='fwidth'>
                    <div id={style.headerBottom} className="container">
                        <div className={style.logoWrap}>
                        <img
                                src="/logo.png"
                                alt="website logo"
                                width={550}
                                height={120}
                            />
                             {/*
                             
                            <Image
                                src="/../public/logo.png"
                                alt="website logo"
                                width={550}
                                height={120}
                                layout="fill"
                            />
                            */}
                        </div>
                        <div className={style.menuWrap}>
                            <ul className={style.menuList}>
                                <li><Link href="/"><a className={style.active}>Home</a></Link></li>
                                <li><Link href="/"><a>Service<span className='icon-angle-down'></span></a></Link>
                                    <ul>
                                        <li><Link href="/">Hijama</Link></li>
                                        <li><Link href="/">Accupuncture</Link></li>
                                        <li><Link href="/">Rukeya</Link></li>
                                    </ul>
                                </li>
                                <li><Link href="/">About</Link></li>
                                <li><Link href="/">Contact</Link></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </>
    );
};

export default Header;