import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import style from '../styles/Header.module.scss';
import Menu from './Menu';

const Header = () => {
    const menuItem = [
        {
            "name": "Home",
            "path": "/",
            "icon": "fa-movie"
        },
        {
            "name": "Service",
            "path": "#",
            "icon": "fa-movie",
            "subitem": [
                {
                    "name": "Hijama",
                    "path": "/hijama",
                    "icon": "fa-movie"
                },
                {
                    "name": "Acupuncture",
                    "path": "/acupuncture",
                    "icon": "fa-movie"
                },
                {
                    "name": "Rukeya",
                    "path": "/rukeya",
                    "icon": "fa-movie"
                }
            ]
        },
        {
            "name": "About",
            "path": "#",
            "icon": "fa-movie"
        },
        {
            "name": "Contact",
            "path": "#",
            "icon": "fa-movie",
            "subitem": [
                {
                    "name": "Chate",
                    "path": "/movie/Friday",
                    "icon": "fa-movie"
                },
                {
                    "name": "Map",
                    "path": "/movie/Old-School",
                    "icon": "fa-movie"
                }
            ]
        }
    ]
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id={style.headerWrap}>
                <div id={style.headerTopWrap} className="fwidth">
                    <div id={style.headerTop} className="container">
                        <div className={style.socialInfoWrap}>
                            <a href='#' className='icon-facebook'></a>
                            <a href='#' className='icon-twitter'></a>
                            <a href='#' className='icon-youtube-play'></a>
                            <a href='#' className='icon-pinterest'></a>
                            <a href='#' className='icon-instagram'></a>
                            <a href='#' className='icon-linkedin'></a>
                        </div>
                        <div className={style.contactInfoWrap}>
                            <div className={style.contactInfo + " icon-phone"}>+880 1681509033</div>
                            <div className={style.contactInfo + " icon-clock"}>Mon-Fri 9:00 am - 7:00 pm</div>
                            <div className={style.contactInfo + " icon-mail"}>assunnahhijama@gmail.com</div>
                            <div className={style.contactInfo + " " + style.resForm}>Reservation Form</div>
                        </div>
                    </div>
                </div>
                <div className='fwidth'>
                    <div id={style.headerBottom} className="container">
                        <div className={style.logoWrap}>
                            <img
                                src="/logo.png"
                                alt="website logo"
                                width={550}
                                height={120}
                            />
                        </div>
                        <Menu menuItem={menuItem}/>
                    </div>
                </div>
            </div>

        </>
    );
};

export default Header;